In [1]:
import numpy as np

### First task of HW_1

In [2]:
a = np.array([5,2])

In [4]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])

In [5]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [8]:
mean_a = a.mean(axis=0)

In [10]:
mean_a

array([2. , 8.4])

### Second task of HW_1

In [12]:
a_centered = a - mean_a

In [13]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Third task of HW_1

In [59]:
a_centered_sp = a_centered[:, 0] @ a_centered[:, 1]

In [56]:
a_centered[:, [1]]

array([[-2.4],
       [-0.4],
       [ 2.6],
       [ 1.6],
       [-1.4]])

In [60]:
a_centered_sp

8.0

In [21]:
N = 5

In [27]:
cov_1 = a_centered_sp / (N - 1)

In [28]:
cov_1

2.0

### Forth task of HW_1

In [30]:
at = a.T

In [31]:
at

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [32]:
cov_2 = np.cov(at, a)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

#### так как она ругается и непонятно на что именно, то попробуем её обмануть

In [33]:
add_a = np.zeros((5, 3))

In [34]:
add_a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
result = np.hstack((a, add_a))

In [36]:
result

array([[ 1.,  6.,  0.,  0.,  0.],
       [ 2.,  8.,  0.,  0.,  0.],
       [ 3., 11.,  0.,  0.,  0.],
       [ 3., 10.,  0.,  0.,  0.],
       [ 1.,  7.,  0.,  0.,  0.]])

In [37]:
rt = result.T

In [38]:
rt

array([[ 1.,  2.,  3.,  3.,  1.],
       [ 6.,  8., 11., 10.,  7.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [48]:
cov_2 = np.cov(rt, result)

In [49]:
cov_2

array([[ 1.  ,  2.  ,  0.  ,  0.  ,  0.  , -0.25, -0.5 , -0.75, -0.75,
        -0.25],
       [ 2.  ,  4.3 ,  0.  ,  0.  ,  0.  , -1.2 , -2.  , -2.9 , -2.8 ,
        -1.3 ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ],
       [-0.25, -1.2 ,  0.  ,  0.  ,  0.  ,  6.8 ,  9.  , 12.35, 11.2 ,
         7.95],
       [-0.5 , -2.  ,  0.  ,  0.  ,  0.  ,  9.  , 12.  , 16.5 , 15.  ,
        10.5 ],
       [-0.75, -2.9 ,  0.  ,  0.  ,  0.  , 12.35, 16.5 , 22.7 , 20.65,
        14.4 ],
       [-0.75, -2.8 ,  0.  ,  0.  ,  0.  , 11.2 , 15.  , 20.65, 18.8 ,
        13.05],
       [-0.25, -1.3 ,  0.  ,  0.  ,  0.  ,  7.95, 10.5 , 14.4 , 13.05,
         9.3 ]])

In [41]:
cov_2[0, 1]

2.0